name: deploy-manager

on:
  workflow_dispatch:
    inputs:
      image_version:
        description: "image version"
        required: true
        default: "latest"

      env:
        description: "environmet name"
        required: true
        default: "production"
        type: choice
        options:
          - development
          - production
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: check inputs
        run: |
          echo "${{ github.event.inputs.image_version }}"
          echo "${{ github.event.inputs.env }}"

      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          package_json_file: ./packages/cdk/package.json

      - run: pnpm i --frozen-lockfile
        working-directory: ./packages/cdk

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.OIDC_ROLE_ARN }}
          aws-region: ap-northeast-2

      - run: |
          NODE_ENV=${{ github.event.inputs.env }} \
          IMAGE_VERSION=${{ github.event.inputs.image_version }} \
          pnpm cdk deploy --require-approval never
        working-directory: ./packages/cdk
