name: push-ci

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2

      - if: startsWith(github.ref, 'refs/heads')
        run: |
          pnpm install --frozen-lockfile
          NODE_ENV=development pnpm test

      - if: startsWith(github.ref, 'refs/tags')
        run: |
          pnpm install --frozen-lockfile
          NODE_ENV=production pnpm test

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2

      - if: startsWith(github.ref, 'refs/heads')
        run: |
          pnpm install --frozen-lockfile
          NODE_ENV=development pnpm build

      - if: startsWith(github.ref, 'refs/tags')
        run: |
          pnpm install --frozen-lockfile
          NODE_ENV=production pnpm build
