name: push-image

on: [push]

jobs:
  push-image:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: docker/setup-buildx-action@v3
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.OIDC_ROLE_ARN }}
          aws-region: ap-northeast-2

      - uses: docker/login-action@v3
        with:
          registry: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-northeast-2.amazonaws.com

      - name: push dev
        uses: docker/build-push-action@v5
        if: startsWith(github.ref, 'refs/heads')
        with:
          push: true
          tags: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-northeast-2.amazonaws.com/nest:${{ github.sha }}
          build-args: |
            NODE_ENV=development
          provenance: false

      - name: push prd
        uses: docker/build-push-action@v5
        if: startsWith(github.ref, 'refs/tags')
        with:
          push: true
          tags: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-northeast-2.amazonaws.com/nest:${{ github.ref_name }}
          build-args: |
            NODE_ENV=production
          provenance: false
