name: push-ci

on: [push]

jobs:
  app_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          package_json_file: ./packages/app/package.json

      - if: startsWith(github.ref, 'refs/heads')
        working-directory: ./packages/app
        run: |
          pnpm install --frozen-lockfile
          NODE_ENV=development pnpm test

      - if: startsWith(github.ref, 'refs/tags')
        working-directory: ./packages/app
        run: |
          pnpm install --frozen-lockfile
          NODE_ENV=production pnpm test

  app_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          package_json_file: ./packages/app/package.json

      - if: startsWith(github.ref, 'refs/heads')
        working-directory: ./packages/app
        run: |
          pnpm install --frozen-lockfile
          NODE_ENV=development pnpm build

      - if: startsWith(github.ref, 'refs/tags')
        working-directory: ./packages/app
        run: |
          pnpm install --frozen-lockfile
          NODE_ENV=production pnpm build
